##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    export DEPLOYPATH=/home/mpdevmyi/public_html
    /bin/cp -R assets $DEPLOYPATH
    /bin/cp tailwind.config.js $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH